#!/usr/bin/env python3
from game.main import Main 
from game.database import SessionLocal, Base, engine

def main():
    # Create tables if not exist
    Base.metadata.create_all(bind=engine)

    # Create ONE session
    session = SessionLocal()

    try:
        game = Main("Banking Simulator", session)
        game.start()
    finally:
        session.close()

if __name__ == "__main__":
    main()
