"""Add Game Empire Asset Currency models

Revision ID: 4986bf1d764e
Revises: 78374277dffb
Create Date: 2026-02-19 17:05:24.889692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4986bf1d764e'
down_revision: Union[str, Sequence[str], None] = '78374277dffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('empires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Float(), nullable=False),
    sa.Column('happiness', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empire_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_cost', sa.Float(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('is_researched', sa.Boolean(), nullable=False),
    sa.Column('research_progress', sa.Float(), nullable=False),
    sa.Column('research_turn_taken', sa.Integer(), nullable=False),
    sa.Column('research_total_turn', sa.Integer(), nullable=False),
    sa.Column('units_produced', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('predict_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empire_id'], ['empires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empire_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empire_id'], ['empires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    op.drop_table('assets')
    op.drop_table('empires')
    op.drop_table('games')
    # ### end Alembic commands ###
