"""add baseline currency fields

Revision ID: 5137dedccff7
Revises: d1afc13552a6
Create Date: 2026-02-20 09:26:42.264521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5137dedccff7'
down_revision: Union[str, Sequence[str], None] = 'd1afc13552a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_baseline', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=False, server_default=sa.text('1.0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('is_baseline')

    # ### end Alembic commands ###
