"""Add domestic_wealth column to empire_balances

Revision ID: 5ecdb98ce9fb
Revises: 79b7055ef11b
Create Date: 2026-02-28 00:03:56.653246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecdb98ce9fb'
down_revision: Union[str, Sequence[str], None] = '79b7055ef11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('SUSTENANCE', 'HEALTHCARE', 'LUXURY', 'CONTRABAND', name='assetcategory'), nullable=False, server_default='SUSTENANCE'))

    with op.batch_alter_table('empire_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domestic_wealth', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empire_balances', schema=None) as batch_op:
        batch_op.drop_column('domestic_wealth')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
