"""Add Bank model

Revision ID: 7b3b60fa3b2e
Revises: 5137dedccff7
Create Date: 2026-02-20 09:54:05.767573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3b60fa3b2e'
down_revision: Union[str, Sequence[str], None] = '5137dedccff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empire_id'], ['empires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empire_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    # ### end Alembic commands ###
