"""Refactor gold to global currency

Revision ID: d1afc13552a6
Revises: 4986bf1d764e
Create Date: 2026-02-19 17:11:18.077303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1afc13552a6'
down_revision: Union[str, Sequence[str], None] = '4986bf1d764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empire_balances',
    sa.Column('empire_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['empire_id'], ['empires.id'], ),
    sa.PrimaryKeyConstraint('empire_id', 'currency_id')
    )
    
    # Data Migration
    connection = op.get_bind()
    
    # Check if Gold currency exists or create it
    # We assume 'Gold' is the global currency name
    gold_currency_id = connection.execute(
        sa.text("SELECT id FROM currencies WHERE name = 'Gold'")
    ).scalar()
    
    if not gold_currency_id:
        # Create Gold currency
        # Since empire_id is optional and None for global, we insert None
        connection.execute(
            sa.text("INSERT INTO currencies (name, symbol, empire_id) VALUES ('Gold', 'G', NULL)")
        )
        gold_currency_id = connection.execute(
            sa.text("SELECT id FROM currencies WHERE name = 'Gold'")
        ).scalar()
        
    # Move gold from empires to empire_balances
    empires = connection.execute(sa.text("SELECT id, gold FROM empires")).fetchall()
    for empire_id, gold_amount in empires:
        if gold_amount > 0:
            connection.execute(
                sa.text("INSERT INTO empire_balances (empire_id, currency_id, amount) VALUES (:eid, :cid, :amt)"),
                {"eid": empire_id, "cid": gold_currency_id, "amt": gold_amount}
            )

    with op.batch_alter_table('empires', schema=None) as batch_op:
        batch_op.drop_column('gold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.FLOAT(), nullable=False, server_default="0.0"))

    # Restore gold logic (simplified: sum all gold currency balances back to empire.gold)
    connection = op.get_bind()
    gold_currency_id = connection.execute(
        sa.text("SELECT id FROM currencies WHERE name = 'Gold'")
    ).scalar()
    
    if gold_currency_id:
        balances = connection.execute(
            sa.text("SELECT empire_id, amount FROM empire_balances WHERE currency_id = :cid"),
            {"cid": gold_currency_id}
        ).fetchall()
        
        for empire_id, amount in balances:
            connection.execute(
                sa.text("UPDATE empires SET gold = :amt WHERE id = :eid"),
                {"amt": amount, "eid": empire_id}
            )

    op.drop_table('empire_balances')
    # ### end Alembic commands ###
